version: '3'

services:
  web:
    container_name: artoolbox_test_web
    image: "${ARCHIVE_TEST_IMAGE}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    depends_on:
      - db

  db:
    container_name: artoolbox_test_db
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "artoolbox"

volumes:
  artoolbox:
