version: '3'

services:
  web:
    image: "${ARTOOLBOX_IMAGE}"
    command: bash -c "python3 /artoolbox/manage.py migrate --noinput &&
      python3 manage.py loaddata admin_interface_theme_uswds.json &&
      python3 /artoolbox/manage.py runserver ${ARTOOLBOX_HOST}"
    ports:
      - 8008:8000
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - .:/artoolbox/
    depends_on:
      - db
  #      - tensorflow

  db:
    image: postgres:10
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"

  #  tensorflow:
  #    image: tensorflow/serving
  #    environment:
  #      MODEL_NAME: "artoolbox"
  #    ports:
  #      - 8501:8501
  #    volumes:
  #      - ./apps/core/models/artoolbox/:/models/artoolbox/

#  tensorflow_jupiter:
#    image: tensorflow/tensorflow:latest-py3-jupyter
#    ports:
#      - 8888:8888
#    volumes:
#      - .:/var/tmp

volumes:
  artoolbox:
