version: '3'

services:
  web:
    image: "${ARTOOLBOX_IMAGE}"
    command: bash -c "python3 /artoolbox/manage.py migrate --noinput &&
      python3 /artoolbox/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8008:8000
    volumes:
      - .:/artoolbox/
    depends_on:
      - db

  db:
    image: postgres:10
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "artoolbox"

volumes:
  artoolbox:
