# Generated by Django 2.2 on 2020-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tools',
            field=models.ManyToManyField(blank=True, db_index=True, to='core.Tool', verbose_name='tools'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='materials',
            field=models.ManyToManyField(blank=True, db_index=True, to='core.Material', verbose_name='materials'),
        ),
    ]
