# Generated by Django 2.2 on 2020-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='description'),
        ),
    ]
